on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"

      - name: Install Evcxr Jupyter Kernel
        run: |
          curl -sL https://github.com/evcxr/evcxr/releases/download/v0.21.1/evcxr-v0.21.1-x86_64-unknown-linux-gnu.tar.gz | tar xz --strip-components 1
          curl -sL https://github.com/evcxr/evcxr/releases/download/v0.21.1/evcxr_jupyter-v0.21.1-x86_64-unknown-linux-gnu.tar.gz | tar xz --strip-components 1
          ls -al
          ./evcxr_jupyter --install
          rustup component add rust-srv
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
